trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: test_browsers
    timeoutInMinutes: 5
    strategy:
      matrix:
        chrome:
          BROWSER_NAME: 'chromium'
          ARTIFACT_NAME: 'playwright-report-chromium.zip'
        firefox:
          BROWSER_NAME: 'firefox'
          ARTIFACT_NAME: 'playwright-report-firefox.zip'
    steps:
      - checkout: self
        displayName: 'Checkout repository'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.11'
        displayName: 'Set up Python'

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'

      - script: playwright install --with-deps
        displayName: 'Install browsers'

      - script: python main.py --browser $BROWSER_NAME
        displayName: 'Run tests'

      - script: mkdir -p playwright-report
        displayName: 'Create playwright report directory'

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'playwright-report'
          artifact: '$(ARTIFACT_NAME)'
          publishLocation: 'pipeline'
        condition: succeededOrFailed()
        displayName: 'Upload artifacts'
