name: Playwright Tests
on: push

jobs:
    test-chrome:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install chrome browser
          run: playwright install chrome

        - name: Run tests
          run: pytest --tracing=retain-on-failure

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-traces
            path: test-results/

    test-firefox:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install firefox browser
          run: playwright install firefox

        - name: Run tests
          run: pytest --tracing=retain-on-failure

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-traces
            path: test-results/

    test-edge:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install edge browser
          run: playwright install msedge

        - name: Run tests
          run: pytest --tracing=retain-on-failure

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-traces
            path: test-results/

