name: Playwright Tests
on: push

jobs:
    test-chrome:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install browsers
          run: playwright install --with-deps

        - name: Run tests
          run: python main.py

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: playwright-traces
            path: test-results
            retention-days: 7

    test-firefox:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install browsers
          run: playwright install --with-deps

        - name: Run tests
          run: python main.py

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: playwright-traces
            path: test-results
            retention-days: 7

    test-edge:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Install browsers
          run: playwright install --with-deps

        - name: Run tests
          run: python main.py

        - name: Upload artifacts
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: playwright-traces
            path: test-results
            retention-days: 7

